# Generated by Django 4.2.5 on 2023-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the destination', max_length=100, unique=True)),
                ('country', models.CharField(help_text='The country where the destination is located', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='A brief description of the destination')),
                ('image', models.ImageField(help_text='A representative image of the destination', upload_to='destination_images/')),
            ],
        ),
    ]
