# Generated by Django 4.2.5 on 2023-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='A representative image of the service', upload_to='service_images/')),
                ('name', models.CharField(help_text='The name of the service', max_length=100, unique=True)),
                ('description', models.TextField(help_text='A brief description of the service')),
            ],
        ),
    ]
