# Generated by Django 4.2.5 on 2023-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_details')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
